### ISSUE TITLE
Change the Layout ?

### ISSUE THREAD

**Issue by Toli1505** [RineshRamadhin/MMM-Lastfm#1]
Hello,

great work thanks but how and where can I change the layout?

**Comment by RineshRamadhin** [comment]
Hi, 

There is a **layout** config option available with which you can select a layout option. You can currently pick between the _default_ layout (large album art, with below the track information), and the _row_ layout (album art beside the track information). _Please refer to the screenshots at the end of the README for examples._

In addition to this you can use the **align** config option to align the album art and track information left or right. _If you don't pass this value it will calculate it based on where you place the module._

```js
{
  module: "MMM-Lastfm",
  position: "top_left",
  header: "Now listening on Last.fm",
  config: {
    apiKey: "LASTFM_API_KEY",
    username: "LASTFM_USERNAME",
    layout: "row",
    align: "right",
  }
},
```

Beside these options you can also use the MagicMirror2 user css file to further overwrite the style as you see fit. I'd recommend to use the DevTools inside your browser for help with this.

Finally if you have any wishes for a specific layout please let me know. I'm also currently exploring some other design looks for this module.
