### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [RineshRamadhin/MMM-Lastfm#4]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with a screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by KristjanESPERANTO** [comment]
@RineshRamadhin Did you noticed this? :slightly_smiling_face:

**Comment by RineshRamadhin** [comment]
Hi Kristjan,

I've added a license file. For now I've picked **CC BY-NC-SA 4.0** which should cover all general MagicMirror usecases as well as your module list.

I will give it some more thought later on, and might change the license to something more permissive, like the MIT license.

**Comment by KristjanESPERANTO** [comment]
Thanks! 🙂 But CC licenses are not recommended for software: _"Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. ..."_ - https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
